### PR TITLE
Update package.json to add ECMAScript esversion 10

### LINKED ISSUE #91: Bump ECMAScript esversion to 10
https://jshint.com/docs/options/ should be verified against package.json, verify default and add 10 to max enum for latest esversion.

### PR DESCRIPTION
**Pull request by asears**
Bump esversion to 10
Fixes #91

### CODE REVIEW

**Comment by asears** [comment]
This may require an upgrade of jshint-server prior to merge to jshint 2.12.0

**Comment by dirdex** [comment]
When will be merged? Actual **esversion** are 11

**Review by metagrapher — APPROVED** [review]
This change looks good to me. I see no reason not to accept and merge to bring this package into 2022/23

I approve, but I don't have write access.

**Comment by metagrapher** [comment]
This is quickly becoming a breaking issue that must be merged.  My teams must disable jshint until it is merged, as this merge fixes a critical blocker.  Would rather not have to fork, patch, and maintain...

@joaomoreno do you think you could approve? 

Thank you!

**Pull request closed without merging**
